PREFIX rdf:     <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX schema: <http://schema.org/>
PREFIX xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX custom: <https://fuseki.dolr.es/ontology/>

SELECT (?ethics_sub AS ?Idéologie) ((?total_f/(?total_h+?total_f))*100 AS ?Pourcentage_de_femmes) (?total_f AS ?Nombre_de_femmes) (?total_h AS ?Nombre_d_hommes)

FROM <http://fuseki.dolr.es/depute/data/parliamentMember>
FROM <http://fuseki.dolr.es/depute/data/organization>
WHERE {
    {
        #Nombre de femmes
        SELECT ?ethics_sub (COUNT(distinct ?depute_f) AS ?total_f)
        WHERE {
            ?depute_f schema:gender "féminin"@fr .
            ?depute_f custom:isActive "1"^^xsd:boolean.
            ?depute_f schema:Organization ?organization .
      		?organization schema:ethicsPolicy ?ethics_sub
        }
        GROUP BY ?ethics_sub ?total_f
    }
  	{
        #Nombre d'hommes
        SELECT ?ethics_sub (COUNT(distinct ?depute_h) AS ?total_h)
        WHERE {
            ?depute_h schema:gender "masculin"@fr .
            ?depute_h custom:isActive "1"^^xsd:boolean.
            ?depute_h schema:Organization ?organization .
      		?organization schema:ethicsPolicy ?ethics_sub
        }
        GROUP BY ?ethics_sub ?total_f
    }
}
GROUPBY ?ethics_sub ?total_f ?total_h
ORDERBY DESC (?Pourcentage_de_femmes)