PREFIX rdf:     <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX schema: <http://schema.org/>
PREFIX xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX custom: <https://fuseki.dolr.es/ontology/>
PREFIX custom_s:  <http://localhost/>

SELECT (?givenName as ?Prénom_Députée_Sénatrice) (?familyName AS ?Nom_Députée_Sénatrice) (?orga_name AS ?Organisation)
FROM <http://fuseki.dolr.es/depute/data/parliamentMember2>
FROM <http://fuseki.dolr.es/depute/data/senateurs>
FROM <http://fuseki.dolr.es/depute/data/organization>
WHERE  {
      ?depute_f schema:givenName ?givenName .
      ?depute_f schema:familyName ?familyName .
      ?depute_f schema:gender "féminin"@fr .
      ?depute_f custom:isActive "true"^^xsd:boolean .

      ?senateur_f custom_s:PCS ?pcs .
      ?senateur_f schema:givenName ?givenName .
      ?senateur_f schema:familyName ?familyName .
      ?senateur_f custom_s:actif "false"^^xsd:boolean .

      ?depute_f schema:Organization ?organization .
      ?organization schema:name ?orga_name .
}
ORDER BY ?familyName
