PREFIX rdf:     <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX schema: <http://schema.org/>
PREFIX xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX custom: <https://fuseki.dolr.es/ontology/>

SELECT (?orga_name AS ?Nom_de_l_organisation) (?orga_date AS ?Date_de_création) (?depute_t AS ?Nombre_de_députés) (?percentage AS ?Pourcentage_de_femmes)

FROM <http://fuseki.dolr.es/depute/data/parliamentMember>
FROM <http://fuseki.dolr.es/depute/data/organization>
WHERE {
    ?organization rdf:type schema:Organization .
    ?organization schema:name ?orga_name .
  	?organization_sub schema:name ?orga_name .
    ?organization schema:foundingDate ?orga_date .

    {
        #Pourcentage de femmes parmis le total
        SELECT ?organization_sub ?depute_t ((COUNT(distinct ?depute_f)*100)/?depute_t AS ?percentage)
        WHERE {
            ?depute_f schema:gender "féminin"@fr .
            ?depute_f custom:isActive "0"^^xsd:boolean.
            ?depute_f schema:Organization ?organization_sub .
        
            # Nombre de députés total
            {
                SELECT ?organization_sub (COUNT(distinct ?depute) AS ?depute_t)
                WHERE {
                    ?depute rdf:type custom:ParliamentMember .
                    ?depute custom:isActive "0"^^xsd:boolean.
                    ?depute schema:Organization ?organization_sub .
                }
                GROUPBY ?organization_sub
            } 
        }
        GROUP BY ?organization_sub ?depute_t
    }
}
GROUPBY ?orga_name ?orga_date ?depute_t ?percentage
ORDERBY DESC(?depute_t) DESC(?percentage)